### ISSUE TITLE
allow anonymizing user questions/answers

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#1]
Changesets for review:
http://github.com/sbuenzli/ese2010-team3/commit/70581b4dc894143c214718fd63eb555c743f2a16
http://github.com/sbuenzli/ese2010-team3/commit/3b5dea87736505607aee37980eb12a7555f5d7e4

**Comment by zombiecalypse** [comment]
Maybe a Null-User would make an easier design?

**Comment by zombiecalypse** [comment]
User interface up and running, pushed to team rep
