### ISSUE TITLE
Edit your Profile

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#11]
Folgende Angaben sollte ein User machen und editieren können: (freiwillig)
- Name und Vorname (ACHTUNG: Username ist fix)
- Alter
- Beruf
- Arbeitgeber
- Website
- Biografie (textarea)
- ...

**Comment by blackyeti-ch** [comment]
Changesets for review:
http://github.com/destiroid/ese2010-team3/commit/703ca0fcb72e5fec2c8c42449d251259132eb705

http://github.com/destiroid/ese2010-team3/commit/14565de43fc947f0afef3016af8a54eba9b649ba

**Comment by blackyeti-ch** [comment]
Test and Null no longer displayed in showprofile:
http://github.com/destiroid/ese2010-team3/commit/6932ab242586a2747db225d75204be75bd5cd704

**Comment by sbuenzli** [comment]
Bis auf einige Details sieht das gut aus!

**Comment by blackyeti-ch** [comment]
Birthday-eingabe implementiert, ausgebessert und gemerged.
