### ISSUE TITLE
password, email, tests and sign up

### ISSUE THREAD

**Issue by mirc0crim** [ese-unibe-ch/ese2010-team3#15]
-the password is now hash encrypted
-emails are now checked with better regular expression
-some tests check those two things
-you can only sign up if the email address is valid

**Comment by sbuenzli** [comment]
http://github.com/mirco89/ese2010-team3/commit/2419e4154f65ed9b57d8c4ca1ec064f4cefbe7a6

**Comment by mirc0crim** [comment]
http://github.com/mirco89/ese2010-team3/commit/2ce0b2c40402b29b225d6184228d9852a815121f
ist so ok?
