### ISSUE TITLE
use a clean database for each unit test

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#16]
Unsere Tests beinflussen sich und die eigentliche Anwendung derzeit gegenseitig (von Tests erstellte Benutzer sind später in der Anwendung sichtbar, etc.). Dies führt zu unzuverlässigen Tests und kann zu unerwarteten und schwer zu findenden Fehlern führen.

Vorschlag: Eine Methode

```
  public static void setTestMode(boolean enable)
```

für User und Question, die User.users bzw. Question.questions am Anfang eines Tests sichert und neu erstellt und am Ende eines Tests die Sicherung wiederherstellt. Dann würden alle Tests beginnen mit

```
  @Before public void setUp() { Users.setTestMode(true); Question.setTestMode(true); }
  @After public void setUp() { Users.setTestMode(false); Question.setTestMode(false); }
```

**Comment by sbuenzli** [comment]
Alternativ/zusätzlich könnten wir auch das Hinzufügen eines Bennutzers zu User.users nicht automatisch im Konstruktor vornehmen sondern nur über eine explizite Methode (register) und diese in den Tests schlicht nicht aufrufen.

**Comment by f3lan** [comment]
So wie ich das sehe, gibt es schon eine Methode register. Vielleicht könnte man beim Aufrufen des Constructors von User immer auf einen default User zeigen. Mit anderen Worten, wenn User initialisiert wird, ist er erst ein default (oder auch anonym) User.

**Comment by sbuenzli** [comment]
Zum Reviewen:
http://github.com/sbuenzli/ese2010-team3/commit/a21279ceed5677f00f43c05fd1f2272854be2ed3
http://github.com/sbuenzli/ese2010-team3/commit/9c9084dd5f3e857802157b2ea8aa9757852155cf
