### ISSUE TITLE
in views: consistently use #{userName} tag

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#17]
Da question.owner(), etc. auch null sein kann (anonymer Benutzer) sollten wir konsistent den Tag verwenden:

```
  #{userName question}
  #{userName answer}
  #{userName comment}
```

**Comment by f3lan** [comment]
Werde mich dem mal annehmen.

**Comment by f3lan** [comment]
Mir ist aufgefallen, dass ein tag in tag nicht funktioniert. Dies stellt ein Problem dar, da z.B: [in commentAnswer.html](http://github.com/ese-unibe-ch/ese2010-team3/blob/master/qa/app/views/Application/commentAnswer.html)

<pre>#{set title:'ajopi - Answer by ' + answer.owner().name /}</pre>

durch

<pre>[#{set title:'ajopi - Answer by ' + #{userName answer /} /}</pre>


ersetzt werden müsste. Habe keine Lösung zur Umgehung gefunden. Hat mir da jemand Rat?

**Comment by sbuenzli** [comment]
Analog zur question.html:

```
  #{set title:'ajopi - ' + answer.summary() /}
```

**Comment by f3lan** [comment]
Review:

http://github.com/flangenegger/ese2010-team3/commit/a6e1c545b2d3c9d984f4c7364b69386e08b70ba0

Habe die if-Schleifen nicht beachtet. Denke da ist der Fall eh klar. Ist das so ok?

**Comment by sbuenzli** [comment]
Ja, super, vielen Dank.
