### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#18]
# Wichtig

Wir sollten unsere Test-Covarge im Auge behalten
#### Report aus Cobertura:
- Answer (77%)
- **Application (8%)**
- **Bootstrap (0%)**
- **Check (N/A)**
- Cobertura (36%)
- Comment (90%)
- **DocViewerPlugin (13%)**
- Entry (87%)
- EntryComperator (75%)
- IDTable (100%)
- Item (80%)
- **PlayDocumentation (0%)**
- Question (81%)
- **Secure (1%)**
- **Secured (0%)**
- **Security (0%)**
- User (89%)
- Vote (100%)
  *******
  Was denkt ihr, wie können wir das besser handeln?
  **Mein Vorschlag:** Jeder Reviewer muss zusätzlich die Test-Coverage überprüfen, wenn diese zu klein ist, so muss dies an den Entwickler zurück gehen.

**Comment by sbuenzli** [comment]
Der Einfachheit halber würde ich es vorerst einmal dabei belassen, für sämtliche Änderungen in models/\* pro geänderte Methode mindestens einen zusätzlichen Test zu fordern, was einfacher überprüfbar ist und etwa ähnlich effektiv. (Bonuspunkte für je einen zusätzlichen Test pro Verzweigung (d.h. zwei Tests pro if-Statement) und je einen zusätzlichen Test pro Fehlerbedingung.)

Übrigens: Müssen wir Klassen ausserhalb models/\* überhaupt prüfen, wenn nur Unittests gefordert sind?

**Comment by f3lan** [comment]
Wird mit Issue #24 bearbeitet.
