### ISSUE TITLE
Show statistics

### ISSUE THREAD

**Issue by tbrog** [ese-unibe-ch/ese2010-team3#19]
# Show statistics:
- Number of answers + per Day/Week/Month
- Number of questions + per Day/Week/Month

Acceptance ratio:
- how much "best" answer(s) <br>
- how much high rated answers (1-10)

**Comment by sbuenzli** [comment]
Ich habe unseren Kunden eigentlich so verstanden, dass diese Statistiken per User erstellt werden sollten und nicht über sämtliche User, wie im Patch http://github.com/tbrog/ese2010-team3/commit/2cb8e6b4ea2f99475324a4f5dd1c2177eba5b0a1 implementiert (z.B. könnte die Anzahl bester Antworten über alle User gerade der Anzahl Fragen entsprechen, dann wäre eher die Anzahl bester Antworten eines spezifischen Users interessant). Wie seht Ihr das?

**Comment by tbrog** [comment]
Update: http://github.com/tbrog/ese2010-team3/commit/ce60d1a55f053266112a44f9d490744d47716f5a

Ich dachte halt, er wolle eine Gesamtstatistik, weil wir ja noch mit ihm über die User Aktivität gesprochen haben.
Man könnte natürlich die individuelle Statistik zusätzlich im Profil des Users anzeigen.

**Comment by tbrog** [comment]
Habe Tests eingefügt. Beim User zeigt es jetzt noch nicht die Anzahl Fragen über die Zeit an. Ich bin mir gerade nicht sicher, wie das am besten zu lösen wäre. Wird bei der User-Anmeldung irgendwo schon ein Timestamp generiert, den ich nutzen könnte? Ich habe nichts dergleichen gesehen, aber vielleicht seh' ichs einfach nicht.
Update:

http://github.com/tbrog/ese2010-team3/commit/a7df6d5f299256681b6e717eacf99eb9de4f5155

**Comment by tbrog** [comment]
Update: http://github.com/tbrog/ese2010-team3/commit/f70539d3a28fa0ba33dff518e67b11f862e65be5

Bräuchte noch eine Review und Kommentar zu obigem Beitrag.

**Comment by tbrog** [comment]
Hier muss ich noch die Time-Methoden anpassen.

**Comment by sbuenzli** [comment]
Gibt's hier noch was zu tun?

**Comment by tbrog** [comment]
Ja: https://github.com/tbrog/ese2010-team3/commit/fb3e8ee7a9446577010efb5fc63d8f240c8f0949

Das Startdatum musste ich trotzdem anders anpassen, da sonst Infinity angezeigt würde.

**Comment by f3lan** [comment]
Kann man diesen Issue eigentlich nicht schon lange schliessen?

**Comment by tbrog** [comment]
Damit dürfte der Issue endlich erledigt sein.
