### ISSUE TITLE
add/delete comments on questions and answers

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#2]
Changesets for review:

http://github.com/flangenegger/ese2010-team3/commit/ea9d52dd028524ac27486db08be045b413906fa6

Frage: Einige Methoden betreffend Comment werden von der Question and Answer genau gleich gebraucht. Wäre es möglich diese in de models.Entry zu verschieben, so dass es kein "dublicated code" mehr hätte? Habe dies noch nicht getan, weil ich nicht eigenmächtig Designentscheidungen tätigen will.

**Comment by sbuenzli** [comment]
Zur Frage: Solange Du die Methoden-Namen/Signaturen beibehalten kannst, ist ein Zusammenführen von Code in Entry keine Design-Änderung sondern reines Refactoring. Das kannst Du ungefragt machen.

Das Ändern von einzelnen Methoden-Namen/Signaturen (wie's eventuell hier der Fall ist), führt eventuell später zu Merge-Konflikten, ändert aber am Design auch nichts Grundlegendes (das solltest Du mit dem Reviewer abwägen können).

Wie wir mit grösseren Design-Anpassungen umgehen, sollten wir nächste Woche in einer Sitzung kurz diskutieren (zusammen mit der Verteilung weiterer Verantwortlichkeiten).

Nebenbei: Hast Du die Tests hinzuzufügen vergessen oder wartest Du damit noch zu?

**Comment by f3lan** [comment]
Vielen Dank für die Antwort: Habe mir aber mir inzwischen überlegt, ob es nicht sinnvoller wäre eine Commentable-Klasse einzuschieben. Diese würde von der Entry Klasse erben. Ein Comment wäre somit eine Entry und Answer und Question ein Commentable. 

Die Test werden nicht von mir behandelt, sondern von Tobias. Er schreibt somit das view und die Tests. 

Schreibe morgen mal eine Traktandenliste im wiki für das nächste meeting.

**Comment by sbuenzli** [comment]
Nach KISS würde ich eher auf eine Zwischen-Klasse verzichten, wenn sie nicht nötig ist (das Kommentieren von Kommentaren sollte bloss nicht durch einen Controller möglich sein, was ohne eine weitere Code-Zeile bereits der Fall ist).

**Comment by f3lan** [comment]
Können wir die Lösung auf den Master pushen?

**Comment by sbuenzli** [comment]
Wenn Tobias auch Deine Beiträge durchgesehen hat, ja klar.

**Comment by f3lan** [comment]
Ok, werde dies morgen mit tobias no besprechen und dann mal pushen.

**Comment by f3lan** [comment]
12.10.2010 done by tbrog and flangenegger
