### ISSUE TITLE
Notation: Date of birth

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#22]
- Wenn die Notation nicht eingehalten wird, sollte eine Meldung erscheinen

**Comment by mirc0crim** [comment]
Wie wärs mit irgend einer Art von Dropdown Menu? Dann muss nie eine Meldung angezeigt werden, die Notation ist eindeutig und als User fände ich das besser..

**Comment by sbuenzli** [comment]
Vorschlag: Wir beschränken uns auf dd.MM.yy (optional noch dd.MM.yyyy) und verwenden zusätzlich den jQuery UI Datepicker von _http://jqueryui.com/demos/datepicker/_, was wohl am Benutzerfreundlichsten wäre. Falls letzteres zu aufwändig ist, würde ich mich auf ersteres beschränken (Eingaben mit einzelnen Dropdown Menus sind m.E. umständliche Fingerübungen).

**Comment by mirc0crim** [comment]
Ein Datepicker sieht natürlich noch viel besser aus

**Comment by blackyeti-ch** [comment]
Closed for the moment (the customer seems to be ok the way it is)
