### ISSUE TITLE
Function-Test && Cleanup Unit-Tests

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#24]
- Implementation der Function-Tests
- Bereinigung der Unit-Tests

**Comment by zombiecalypse** [comment]
http://github.com/zombiecalypse/ese2010-team3/commit/138e19ca136d59726d67d212f09eb898d06fb694
Der Test des Controllers funktioniert nicht, da das Framework sich gegen Calls an den Secured Controller sträubt. Die Testcoverage des model ist aber 92%

**Comment by f3lan** [comment]
reviewed
