### ISSUE TITLE
User Deletion

### ISSUE THREAD

**Issue by zombiecalypse** [ese-unibe-ch/ese2010-team3#3]
With this, the user can delete themselves from the database:
http://github.com/zombiecalypse/ese2010-team3/commit/d67855b56eeb49e67fa301a2dd0c693bb2ddad2c

**Comment by sbuenzli** [comment]
Könntest Du mir im Gegenzug bitte issue 1 reviewen?

**Comment by zombiecalypse** [comment]
Sicher, soll ich gleich die beiden mergen und das Interface kombinieren?

**Comment by zombiecalypse** [comment]
Ist gemerged und alles scheint zu funktionieren. Ist im team rep
