### ISSUE TITLE
Refactor recent activities + link comments

### ISSUE THREAD

**Issue by blackyeti-ch** [ese-unibe-ch/ese2010-team3#32]
- use getQuestion/getAnswer for adding recent questions (compare timestamps)
- link to comments

**Comment by blackyeti-ch** [comment]
Part 1: Changed to the use of getQuestions/Answers/Comments
http://github.com/destiroid/ese2010-team3/commit/a3e53a9f745dc92dca78757672ae50ec0321fbdc

**Comment by sbuenzli** [comment]
Wer soll die Änderung reviewen? Mirco oder Tobias?
