### ISSUE TITLE
Refactor correct notation for getters & setters

### ISSUE THREAD

**Issue by blackyeti-ch** [ese-unibe-ch/ese2010-team3#33]
- Some getters and setters are not named with getX/setX
- JavaDoc cleanup

**Comment by sbuenzli** [comment]
Gehört _http://github.com/destiroid/ese2010-team3/commit/f441cc820ca1d1ca6586fd71cc5ad187431f6c14_ zu diesem Issue? Wer soll's denn reviewen?

**Comment by blackyeti-ch** [comment]
http://github.com/destiroid/ese2010-team3/commit/919dd6cf8a1e0adfce2fa7f578f7344b0cd2ca06
kann man eigentlich auch dazu nehmen, Wer Zeit hat kann reviewen, ist ja keine Story, stresst nicht.

**Comment by sbuenzli** [comment]
Je länger Du wartest, desto mehr Merge-Konflikte handelst Du Dir ein...
