### ISSUE TITLE
answer watching: optional notifications for new answers

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#35]
Model-Änderungen zum Reviewen: _http://github.com/sbuenzli/ese2010-team3/commit/4028a3e7f68b598884e1d543b7f238de809d75de_

Noch ausstehend sind in der View:
- Notifications Inbox View (inklusive Möglichkeit, Notifications als gelesen zu markieren und zu löschen)
- Notifications Counter neben dem Log-out Link
- Gut sichtbarer Hinweis bei ganz neuer Notification

**Comment by sbuenzli** [comment]
View-Änderungen zum Reviewen: _http://github.com/sbuenzli/ese2010-team3/commit/b5fdbedca2945e491837f6da916d457382c63b56_

Sieht noch nicht ganz so hübsch aus, aber die Funktionalität sollte vollständig vorhanden sein.

**Comment by sbuenzli** [comment]
Nachbesserungen zum Reviewen: _http://github.com/sbuenzli/ese2010-team3/commit/c9b68a7e972c529c64991243b313eac8d2696f66_

Das Aufräumen der View überlasse ich dann gerne Felix. :-)

**Comment by f3lan** [comment]
Hier noch meine kleinen Änderungen:

http://github.com/sbuenzli/ese2010-team3/commit/ac20f69750a2c0bd53b2b7c5a067c31be0519953

**Comment by mirc0crim** [comment]
Musste paarmal zwischen den vier commits hin und her wechseln zum reviewen :) JavaDoc ist überall und Namensgebung ist gut, so lässt es sich schnell lesen. Deine Änderungen überzeugen und die letzten Kleinigkeiten die ich gesehen habe hat Felix bereits gemacht.

**Comment by sbuenzli** [comment]
Mit einer kleinen Änderung gemerget.
