### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by zombiecalypse** [ese-unibe-ch/ese2010-team3#36]
Make a search box available for full text and tag search.

**Comment by zombiecalypse** [comment]
macht Suche in Fragentext und -tags:
http://github.com/zombiecalypse/ese2010-team3/commit/18139ca93a4cbd0f717626376788af72899f9c59

Für das Testen ist ausserdem die Datenbank drin: http://github.com/zombiecalypse/ese2010-team3/commit/cd701c011cea624759ff893b9258a83b3fe3b6af

Und hier der View:
http://github.com/zombiecalypse/ese2010-team3/commit/24903f75a13ddf86cd5b5fb24c5c9b2951f130b2

**Comment by sbuenzli** [comment]
Zum Ordnen der Fragen: Question.sortMapByValue von _http://github.com/tbrog/ese2010-team3/commit/329e8e6681941486cb02fda869575d2b73b82ad3_

**Comment by sbuenzli** [comment]
Im Hinblick auf die Usability tests: als Benutzer würde ich erwarten, dass insbesondere auch die Antworten durchsucht werden.

**Comment by sbuenzli** [comment]
Auch erwarten würde ich, dass der Suchterm weiterhin im Suchfeld angezeigt wird, so dass ich eine Suche einfach anpassen könnte (à la Google, etc.).

**Comment by sbuenzli** [comment]
Schliesslich hätte ich erwartet, dass mehrere Suchterme die Suche einschränken und nicht ausweiten (AND statt OR, wie bei Google, etc.).

**Comment by sbuenzli** [comment]
Für meinen ersten Punkt habe ich Issue 47 eröffnet und die letzten zwei Punkte habe ich im Issue 43 implementiert. Könntest Du diese bitte reviewen.

Hier sind noch einige wenige Review-Kommentare offen, bevor dieser Issue geschlossen werden kann.
