### ISSUE TITLE
Recommend tags from question

### ISSUE THREAD

**Issue by mirc0crim** [ese-unibe-ch/ese2010-team3#37]
Keywords aus der Question sollten als Tags vorgeschlagen werden

-Wörter mit 3 oder weniger Buchstaben werden nicht beachtet <br>
-Wörter nach Häufigkeit sortieren und die 5 ersten Vorschlagen

**Comment by mirc0crim** [comment]
Frage: Wie kann ich den content der Question bekommen, wenn dieser noch nicht abgesendet wurde? Die Question existiert da bei uns ja noch nicht. Von jQuery und Ajax habe ich nicht wirklich eine Ahnung. Das zerlegen in Keywords anschliessend ist dann wohl kein Problem mehr.

**Comment by sbuenzli** [comment]
Füg dem Textfeld in index.html (und wo immer es sonst noch auftritt) _id="newQuestion"_ hinzu, dann kannst Du mit
      $("#newQuestion").val()
auf dessen Inhalt zurückgreifen, ihn ggf. etwas vorverarbeiten und dann in qa.js in TagAutocompletion.source in der Zeile unter "term:" zur JSON-Anfrage hinzufügen (nicht vergessen, in der "term:" Zeile ein Komma anzuhängen). Also z.B. vorerst einmal
      content: ($("#newQuestion").val() || "").split(/(?:^|\W+)(?:\w{1,3}(?:\W+|$))_/).join(",")
(ungetestet), was Dir in der Anfrage die neue Variable *content_ mit einer Komma-getrennten Liste von längeren Wörtern ergeben sollte.

**Comment by mirc0crim** [comment]
Danke!

**Comment by mirc0crim** [comment]
Ich habs also doch noch geschafft! :)
http://bit.ly/938zU6

**Comment by mirc0crim** [comment]
und brauchen wir dass? (unique usernames) http://bit.ly/bZRHJl

**Comment by sbuenzli** [comment]
"unique usernames" sieht nach einer sinnvollen Stabilisierung aus.

Beim Schreiben der Tests für den anderen Patch, teste bitte unter anderem, dass für "abc abcd abce abcf" kein Wort vorgeschlagen wird und dass bei längeren Texten nicht mehr als 5 Wörter vorgeschlagen werden (der Häufigkeit nach sortiert).

In einer späteren Iteration könnten wir zudem noch Aarons StopWords-Liste verwenden, um Wörter herauszufiltern, die aus sprachlichen und nicht inhaltlichen Gründen häufig auftreten.

**Comment by mirc0crim** [comment]
habs doch endlich geschafft:
https://github.com/mirco89/ese2010-team3/commit/b006dce9dcfe9726badcfabc6304b4c911082353

**Comment by sbuenzli** [comment]
Hier fehlt noch der Merge mit dem upstream master.

**Comment by mirc0crim** [comment]
erledigt
