### ISSUE TITLE
Watchinglist

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#39]
Wollte eben gerade die Watchingliste implementieren. Leider bin ich gerade vom Code ein weinig verwirrt. Kann ich alle gewatchten Elemente vom User abfragen? Ich dachte erst, dass jedes Objekt, welches von einem bestimmten User gewatched wird, könnte man beim User speicher. Da wir jetzt aber eine Datenbank haben, wäre es wohl besser, dies würde dort gespeichert werden. Kannst du mir da ein Tipp geben?

**Comment by sbuenzli** [comment]
Derzeit musst Du diese Information wohl aus der DB herausprügeln: über alle Fragen iterieren und all jene herauspicken, für die question.hasObserver(user) gilt.

**Comment by f3lan** [comment]
So das wars schon:

for review:

https://github.com/flangenegger/ese2010-team3/commit/560e5c4540cfb66a63051c51d40da68c0aef2590

https://github.com/flangenegger/ese2010-team3/commit/59a48e0d896f3e19dd30e2e1205f11450bb3709c
