### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#40]
Habe diesen Issue  für ein kleines Brainstorm eröffnet.
# Wie soll ein Usecase aussehen?
1. User soll ein sich registrieren
2. User soll sich aus- und einloggen
3. U. soll eine Frage stellen
4. U. soll eine Frage beantworten
5. U. soll eine Comment zu einer Frage und einer Antwort erstellen
6. U. soll eine Frage und eine Antwort voten
7. U. soll ein Profile eines anderen User betrachten
8. U. soll dessen letze Frage/Antwort betrachten
9. U. soll sein Profile bearbeiten
10. U. soll eine Question watchen
11. U. soll eine Best Answer auswählen
12. U. soll sich Löschen

Bitte diese Liste vervollständigen und verändern!

**Comment by sbuenzli** [comment]
1. User soll eine Frage zu gegebenem Stichwort finden
2. User soll eine eigene Frage (nachträglich) mit sinnvollen Tags versehen
