### ISSUE TITLE
link tags to search

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#43]
Unser Kunde hat bereits versucht, einen Tag anzuklicken. Nun, da wir eine Suchfunktion haben, sollte dies einfach in der View zu implementieren sein.

**Comment by sbuenzli** [comment]
Zum Reviewen: https://github.com/sbuenzli/ese2010-team3/commit/3d460e194ea27c1aaa20aa39d591d274836ac282 und https://github.com/sbuenzli/ese2010-team3/commit/efaa0c85b214e5470b0ecb7b64f2d77bdccc6e88

**Comment by zombiecalypse** [comment]
Gesichtet worden, kannst es pushen

**Comment by sbuenzli** [comment]
Danke.
