### ISSUE TITLE
search answers as well

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#47]
Ein uneingeweihter Benutzer wird wohl erwarten, dass auch Antworten durchsucht werden (bei holprig gestellten Fragen kommen gewisse Stichworte eventuell erst in den Antworten vor).

Die einfache Lösung besteht hier wohl darin, in SearchFilter.rateText den content aller Antworten zu einer Frage mit jenem der Frage zu konkatenieren und dann darüber zu suchen.

Die komfortabler Lösung könnte darin bestehen, dass SearchFilter nicht Fragen sondern allgemein Entries durchsucht und diese dann einzeln anzeigt.

**Comment by zombiecalypse** [comment]
Die komfortablere Lösung hat noch das Problem, dass Antworten zu Fragen angezeigt würden, welche bereits in den Ergebnissen sind. Ich bin mir nicht wirklich sicher, was der durchschnittliche Benutzer erwarten würde. Ich zB würde keine Antworten erwarten, oder vllt dass eine Frage angezeigt würde, zu der eine passende Antwort eingegangen ist, aber nicht, dass die Antwort selbst auftaucht, weil das zu vielen falsch positiven führen würde. 
Am besten klären wir das mit dem Kunden direkt, was er von der Suchfunktion erwartet, schliesslich bezahlt er dafür ;)

**Comment by zombiecalypse** [comment]
Die einfache Lösung steht: https://github.com/zombiecalypse/ese2010-team3/commit/b07903edaac882af5d2a69a3ac443538dc225398
hier werden die Antworten nach Volltext durchsucht und das Ergebnis mit dem Rating des Fragentexts und der Tags verrechnet. Die AND-Suche bleibt bestehen, wobei alle Suchbegriffe entweder in
- Tags der Frage
- Volltext der Frage
- Volltext einer der Antworten

auftauchen müssen, damit eine Frage gezeigt wird. 

Der nächste Schritt wäre, die beste passende Antwort (sollte eine solche existieren) mit der Frage mitanzuzeigen. Das ist aber nicht nahtlos in der jetzigen Suche möglich.

**Comment by f3lan** [comment]
Alter Issue! Geht hier noch was?

**Comment by zombiecalypse** [comment]
Rein theoretisch steht die komplexere Lösung, aber ist noch nicht ausführlich getestet und der Customer hat das wohl vergessen

**Comment by zombiecalypse** [comment]
zombiecalypse/ese2010-team3@7e80c1b
zombiecalypse/ese2010-team3@c0116e5
zombiecalypse/ese2010-team3@e87e67b
sind die commits
