### ISSUE TITLE
Suggest other question that the user might know to answer

### ISSUE THREAD

**Issue by tbrog** [ese-unibe-ch/ese2010-team3#49]
Depends on expertise

**Comment by sbuenzli** [comment]
Ja, das Anzeigen von "Expertise" in der View wäre eigentlich als eigene Story gedacht gewesen.

**Comment by tbrog** [comment]
Update: https://github.com/tbrog/ese2010-team3/commit/43e8ce025b60ced5f2af4086ef3347c0efe25f79

Ups, ja das stand ganz klein auf meiner Karte. 

Die vorgeschlagenen Fragen werden aufgrund des Ratings für die Antworten des Users bei ähnlichen Fragen sortiert. Fragen bei denen die Antworten des Users negativ bewertet wurden, werden nicht aufgenommen. Bereits beantwortete Fragen oder eigene Fragen auch nicht. Ebenso werden Fragen nicht angezeigt, bei denen bereits eine bestAnswer existiert, oder die älter als 120 Tage sind.

Im Moment werde die 6 ersten Fragen vorgeschlagen.

**Comment by sbuenzli** [comment]
Deine Heuristik tönt einleuchtend.

**Comment by tbrog** [comment]
Update: https://github.com/tbrog/ese2010-team3/commit/7e2f3d2b852f2273049ea477395ac790398cd99b

Kleine Änderung: https://github.com/tbrog/ese2010-team3/commit/718fcb457b9ecf55a0a4f274eea510b6b114b5f6

**Comment by sbuenzli** [comment]
Sieht gut aus, jetzt fehlt bloss noch das Beheben einiger Merge-Konflikte...
