### ISSUE TITLE
polish view

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#51]
- | bei Unlock entfernen
- eigene Frage hervorheben
- notification.html aufräume
- dunkler Balken bei related Question entfernen
- Kommentare verkleinern
- cheaterwarning bei body cleanen

**Comment by f3lan** [comment]
Review:
https://github.com/flangenegger/ese2010-team3/commit/81627fab0f6a437be22ccf30771354bf3e782129

**Comment by zombiecalypse** [comment]
Sieht gut aus, ausser evtl noch das "more" von related Questions auf die selbe zeile wie das related questions nehmen, weil es sonst nach "more Comments" aussieht. Ich hab mir die Freiheit genommen, das ganze mit dem Code-style zu mergen und zu pushen

**Comment by f3lan** [comment]
vielen Dank!
