### ISSUE TITLE
Show only 20 questions on startpage

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#52]
index.html:
- Anzeige der neusten 20 Fragen
- Next und Perv Link
- Such-Pagnation

**Comment by sbuenzli** [comment]
_Perv_ Link ;-)

Gemeint ist Pagination (Navigation mit Nächste/Vorherige-Links durch alle möglichen Fragen), was dann auch für Suchergebnisse auf gleiche Weise möglich sein sollte.

Nach dem Gespräch mit unserem Coach haben wir uns zudem darauf geeinigt, vorerst auf Caching der Hitlists zu verzichten und die Abfragen bei jeder Navigation erneut auszuführen:

“The First Rule of Program Optimization: Don't do it. The Second Rule of Program Optimization (for experts only!): Don't do it yet.” - http://en.wikipedia.org/wiki/Program_optimization#Quotes

**Comment by tbrog** [comment]
https://github.com/tbrog/ese2010-team3/commit/27e2d7b18dca56e5c5f9475eb3091d4d56d6a355

Ist vielleicht noch etwas holprig gemacht. Funktionieren tuts jedenfalls mal :) Tests kommen noch.

**Comment by tbrog** [comment]
Mit Tests: https://github.com/tbrog/ese2010-team3/commit/69e8751d72f4f6d7ee9ff1d7bcb26148be0ab5bf

**Comment by tbrog** [comment]
Noch Tests dazu und pagination der Suche: https://github.com/ese-unibe-ch/ese2010-team3/commit/4b610f37c908d02ab4e2cc0e4722ab3c0e89135a
