### ISSUE TITLE
more usability tweaks

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#53]
- unwatch from notifications.html
- consistently notify for empty lists (no notifications, no answers, etc.)
- display moderator status
- move related questions to the bottom of the page
- consistently notify about current events (notifications, blockings, etc.)

**Comment by sbuenzli** [comment]
Der letzte Punkt fehlt noch: https://github.com/sbuenzli/ese2010-team3/commit/723f06fdb0aacdd19b8ea446f5c0f60ec9865c96

**Comment by sbuenzli** [comment]
Aufräum-Arbeiten:
- https://github.com/sbuenzli/ese2010-team3/commit/d4c2f2f13980c5df5b0740e813e0cb5f321f826c
- https://github.com/sbuenzli/ese2010-team3/commit/8e36255ce7665b6cb818a5509935d4fcf008f825

Der letzte Punkt:
- https://github.com/sbuenzli/ese2010-team3/commit/04da60585f6726bbd721ba7ae5edf5c63c440354

**Comment by f3lan** [comment]
Reviewed

## Usability test

Folgendes war bei einem Usability-Test (nach Issue 40):
[Browser Google Chrome, Ubuntu 10.10, usability-branch]
- User konnte keine Antworten geben (Fehlermeldung: Please don't give empty answers.)
- User konnte beim Bearbeiten des eigenen Profils sein Geburtstag eingeben, die Änderung wurde aber nicht übernommen.
- Beim Klicken in das Geburtstagsinputfeld erscheint rechts schon ein Gutzeichen, auch wenn der User noch nichts eigegebn hat.
- Das finden des Edit Profile war nicht sofort ersichtlich.
- Sign-Up Button sollte vielleicht links sein, da das dropdown-menu den knopf verdeckt.

**Comment by sbuenzli** [comment]
Danke fürs Reviewen. Wir sollten zumindest einige der Tests dann auch mit einem etwas älteren Browser (Firefox 3.6, IE8) durchführen, da diese noch kaum HTML5-Features unterstützen, von welchen wir nun an mehreren Orten gebrauch machen.
- Das Antwort-Problem war auf eine überflüssige Route zurückzuführen - behoben.
- Geburtstage akzeptieren wir offenbar nur mit vierstelliger Jahreszahl - habe die client-seitige Überprüfung angepasst.
- Das Gutzeichen steht da, weil das Geburtstagsfeld optional und dann eine Leereingabe eben korrekt ist.
- Den Link habe ich nach links verschoben (und unten an der Seite verdoppelt) - hoffentlich hilft's.
- Das Vervollständigungs-Dropdown-Menu wirst Du wohl eh schliessen wollen, bevor Du Dich registrierst. Den Submit-Knopf direkt unterhalb der Eingabefelder macht m.E. mehr Sinn, da Du dann (mit der Maus) bloss den Feldern nach unten gehen musst und nicht am Ende noch links und rechts nach dem Knopf "suchen" musst.

**Comment by f3lan** [comment]
Vielen Dank für die Änderungen. Das wegen dem Dropdown-Menu war einfach ein Report aus dem U.-Test. Links macht er wohl eher Sinn.
