### ISSUE TITLE
confirmation & undo for delete questions

### ISSUE THREAD

**Issue by blackyeti-ch** [ese-unibe-ch/ese2010-team3#54]
- When deleting a question there should be a confirmation to avoid accidental deletions
- After a questions was deleted there should be a way to undo this (only the last question that was deleted)

**Comment by sbuenzli** [comment]
Von diesen zwei Punkten benötigen wir bloss einen: wenn das Löschen rückgängig gemacht werden kann, ergibt sich die vorgängige Nachfrage.

**Comment by blackyeti-ch** [comment]
http://fwd4.me/nlN

Wollte eigentlich confirmDeleteQuestion noch in Secured schieben, aber das gab irgendwelche komischen unbind errors vom framework und ich habe noch nicht herausgefunden warum...
