### ISSUE TITLE
XML parsing/import

### ISSUE THREAD

**Issue by zombiecalypse** [ese-unibe-ch/ese2010-team3#56]
Importing XML files should be possible for moderators

**Comment by zombiecalypse** [comment]
Adaption of new xml semantics: https://github.com/zombiecalypse/ese2010-team3/commit/c7d5b6fba419801045bafb92ee6dece2ba4c44ba

Fixes to tests:
https://github.com/zombiecalypse/ese2010-team3/commit/5626d475888816d41d1a65b7f080bb5f1e6c9455
https://github.com/zombiecalypse/ese2010-team3/commit/955e46c274edf826754429a239ba168c3bbfa181

The view for moderators:
https://github.com/zombiecalypse/ese2010-team3/commit/33f99de063bac26f96595e7dc2dfe7938ae71ee1

**Comment by zombiecalypse** [comment]
Admin Interface: https://github.com/zombiecalypse/ese2010-team3/commit/5c759a56d51fc6c70e901d1454ecc4508eda8165

**Comment by zombiecalypse** [comment]
Flattening the admin interface https://github.com/zombiecalypse/ese2010-team3/commit/8b30cafc7ea58cd1158ff069f84ab2ee4f65cc5e

**Comment by zombiecalypse** [comment]
Addendum: the interesting part of the last comment would be here: https://github.com/zombiecalypse/ese2010-team3/commit/33a470e4e7ca6a4dc42152b63eb038470613a0db

**Comment by zombiecalypse** [comment]
Refactoring html: admin interface as definition list:
https://github.com/zombiecalypse/ese2010-team3/commit/ce378173f4fa14075dcf1b57523d3e92881c9af5

**Comment by f3lan** [comment]
Sorry habe nicht gesehen, dass ich dein Code duchsehen muss. Werde dies heute aben noch erledigen.

**Comment by f3lan** [comment]
Bis auf das Problem in Issue 57. OK

Reviewed
