### ISSUE TITLE
Zeilenumbruch 

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#57]
Habe mal eine XML-Datei eingelesen (siehe Issue 56). Dabei ist mir aufgefallen, dass Zeilenumbrüche nicht immer korrekt gemacht werden. Hat jemand eine Idee wie man dies beheben könnte?

**Comment by sbuenzli** [comment]
Mir fällt gerade auf, dass in der XML-Datei davon ausgegangen wird, dass wir in der Lage sind, HTML darzustellen - sind wir aber eigentlich nicht (v.a. aus XSS-Gründen). Was nun?

**Comment by f3lan** [comment]
Stand glaube ich nirgends als Bedingung. Einige Gruppen haben ein Markdown implementiert. Wär das die Lösung?

**Comment by blackyeti-ch** [comment]
"Data that exists in the file but is not implemented in your model can be skipped."
Siehe http://ese.unibe.ch/exercises/Importer-Specification

**Comment by sbuenzli** [comment]
Bloss sind diese Daten die Inhalte der Fragen und Antworten...

Zu Markdown: Das unterstützt auch reines HTML als Eingabe. Kommt da ein Sanitizer mit? Falls ja, wäre dies eine günstige Lösung (dann hätten wir das Zeilenumbruch-Problem auch eleganter gelöst).

**Comment by f3lan** [comment]
Gute Frage. Habe bis jetzt noch keine Schlüssige Antwort. Allerdings jetzt noch ein Markdown einzufügen ist wohl eine ziemliche Übung!

**Comment by sbuenzli** [comment]
Sollte v.a. eine Copy&Paste-Übung sein, wenn wir eine geeignete Bibliothek finden (z.B. https://github.com/sirthias/pegdown ), ggf. in Kombination mit einem HTML Sanitizer (z.B. http://jsoup.org/cookbook/cleaning-html/whitelist-sanitizer ).

**Comment by mirc0crim** [comment]
oder BBCode wäre auch eine Möglichkeit

**Comment by f3lan** [comment]
@sbuenzli Wenn alle gemerged haben dann solte das machbar sein. Hättest du morgen um 10 Uhr Zeit? Wir könnten dann den finisch machen.
@mirco89 Wäre auch eine Möglichkeit, aber Markdown ist mächtiger.

**Comment by f3lan** [comment]
pegdown sieht gut aus. Sieht aber nach mehr als nur Copy&Paste aus. Jedenfalls für mich.

**Comment by sbuenzli** [comment]
Morgen habe ich keine Zeit.

Copy&Paste: https://github.com/sbuenzli/ese2010-team3/commit/61511a04b33cc062f50361484b2760f268bbac05

**Comment by sbuenzli** [comment]
BTW: Für Eclipse wird ein erneutes "play eclipsify qa" benötigt, damit der Classpath für die drei Bibliotheken aktualisiert wird.

**Comment by f3lan** [comment]
OK da bin ich verblüfft! Vielen Dank. Werde morgen ca. ab 10 die tags und branches machen.

**Comment by f3lan** [comment]
by the way: reviewed

**Comment by mirc0crim** [comment]
cool! bitte mergen, ich wills ausprobieren :)

**Comment by sbuenzli** [comment]
Merge complete.

**Comment by sbuenzli** [comment]
Follow-up, so zum _last minute_ reviewen: https://github.com/ese-unibe-ch/ese2010-team3/commit/91d9af8effa8585840151c943fbb4f79485956d6
