### ISSUE TITLE
Moderator - Edit Profile

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#58]
Wenn eine Moderator ein User blockiert, so kann er das Profil des Users danach nicht mehr bearbeiten.

**Comment by sbuenzli** [comment]
Good catch! Da scheint noch einiges mehr schief gegangen zu sein, bzw. war es einem Moderator gar nie möglich, die Daten eines anderen Benutzers zu bearbeiten.

Fix: https://github.com/ese-unibe-ch/ese2010-team3/commit/886fbd41133ac0d8ed242a03e801ba51c191979c
