### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by mirc0crim** [ese-unibe-ch/ese2010-team3#59]
Warum escaped das play framework den input nicht mehr?
Ich kann als frage <script>alert"hallo xss"</script> eingeben ohne das etwas escapet wird und deshalb erscheint die alert box auch bei jedem aufruf der frage.
Allerdings kann ich das problen nicht erkennen...sonst hätte ich auch kein issue eröffnet.
Hat irgend jemand eine idee?

**Comment by sbuenzli** [comment]
Good catch! Das Problem nehm ich auf meine Kappe (und gebe der ungenügenden Dokumentation des Play Frameworks einen Teil der Schuld weiter). nl2br erzeugt nicht nur Zeilenumbrüche, es gibt auch RawData zurück, für welches HTML nicht mehr escaped wird (eigentlich logisch: andernfalls könnte &lt;br> auch nicht korrekt interpretiert werden). Zuvor muss also HTML explizit escaped werden...

Fix: https://github.com/ese-unibe-ch/ese2010-team3/commit/7f602b81df37ae5cae58c133a70e3f240c1f93ca
