### ISSUE TITLE
Comments Design

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#6]
Comments müssen nur noch in eingerückter Form erscheinen. Die "<<" und ">>" sind zu entfernen.

**Comment by f3lan** [comment]
Review:

http://github.com/flangenegger/ese2010-team3/commit/dab5bc7cce991bbce4a0b36c43d4e80b36c033b5

**Comment by mirc0crim** [comment]
Sieht gut aus -> merge
