### ISSUE TITLE
Moderator - Delete an other User

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#61]
Wenn man als Moderator einen anderen User löschen will, kommt das Interface für seinen eigenen User zu löschen.

**Comment by mirc0crim** [comment]
Ein Moderator soll einen User auch nur blocken können, aber doch nicht löschen.
Deshalb in showuser.html ein if user==showuser um die Zeile
<a href="@{Application.deleteuser}">Delete Account</a>
einfügen.
Und testen! :)

**Comment by f3lan** [comment]
Diese Bedingung geht leider nicht, das sich sonst der Moderator nicht mehr selbst löschen kann.
Im eigentlichen würde es Sinn machen, wenn ein Moderator andere User löschen kann. Allerdings beim jetzigen Stand  löscht der Moderator nur sich selbst.

**Comment by mirc0crim** [comment]
versteh ich nicht und macht keinen Sinn...ich habe diesen Abschnitt eingebaut und es funktioniert perfekt:

<a href="@{Application.editProfile(showUser.getName())}">Edit Profile</a>

#{if user==showUser}
    <a href="@{Application.deleteuser}"> | Delete Account</a>
#{/if}

**Comment by mirc0crim** [comment]
hast du etwa showuser geschrieben anstatt showUser mit grossem "U"?

Übrigens müssen wir es dann oben und unten von der Seite einbauen ;)

**Comment by sbuenzli** [comment]
Fix for review: https://github.com/sbuenzli/ese2010-team3/commit/16aec66e1acb06c279e1a19df26f2e76ccd226c5

(landen können wir den Fix wohl erst in einer Woche, wenn wir Zugriff zu "unserem" Repo zurückerhalten)

**Comment by mirc0crim** [comment]
Ich finde es immer noch nicht gut, dass ein Moderator einen anderen User löschen kann.
Wenn der User blockiert wird, bekommt er wenigstens eine Mitteilung, dass er etwas falsch gemacht hat. Aber wenn er gelöschen wurde, so kann er sich einfach nicht mehr einloggen und weiss nicht ob das Passwort falsch ist oder der Username falsch eingegeben wurde. Es denkt wohl niemand daran, dass der Account von einem Mod gelöscht wurde.

**Comment by sbuenzli** [comment]
Ja, das hat was. Anpassung: https://github.com/sbuenzli/ese2010-team3/commit/e1736dc2f321f7988e521503e63f7713893ff9ba

**Comment by mirc0crim** [comment]
mirco89 likes this :D
