### ISSUE TITLE
Aufträge KW 47-48

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#64]
Hat jemand etwas von unserem neuen Kunden gehört? Ansonsten müssen wir wohl ihn kontaktieren. Was haltet ihr davon?

**Comment by mirc0crim** [comment]
Hab noch nichts von Ihn gehört.

**Comment by tbrog** [comment]
Ja wäre wohl besser ihm ne mail zu schicken...eine Woche lang nichts zu tun kann ja nicht in seinem Sinn sein ;)

**Comment by zombiecalypse** [comment]
Jep, ich denke, langsam wirds Zeit. Vllt hat er es an die falsche Addresse geschickt oder sowas.

**Comment by f3lan** [comment]
Ok soeben habe ich bemerkt dass unser Customer ein Mail an uns geschickt hat. Ich werde mal die die Issues dazu eröffnen. Bitte nehmt die Issues an. Ich werde dem Customer morgen ein Mail schreiben, um den Erhalt seines Mails zu bestätigen.
Bitte schreibt in diesem Issue, wenn etwas mit den Aufträgen nicht klar ist oder ob ihr Schwierigkeiten seht in der Umsetzung.

Neue Issues:
- https://github.com/ese-unibe-ch/ese2010-team3/issues#issue/65
- https://github.com/ese-unibe-ch/ese2010-team3/issues#issue/66
- https://github.com/ese-unibe-ch/ese2010-team3/issues#issue/67

Bitte tragt euch bis morgen (29.11) Mittag bei den Issues ein. Vielen Dank und bis Dienstag.

**Comment by sbuenzli** [comment]
Hab alle verbleibenden Issues (63, 65, 66, 68) verteilt. Sollten alle bis morgen Nacht umsetzbar sein...
