### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#65]
Sprache wechseln. Von jeder Seite aus soll es möglich sein die Sprache zu wechseln (dabei gelangt man wieder auf die gleiche Seite), dabei sollten sicherlich Englisch und Deutsch sein und noch alle weiteren die ihr beherrscht oder die ihr übersetzen könnt

**Comment by blackyeti-ch** [comment]
Hrmpf, mühsame schreibarbeit (wir hätten mehr messages brauchen sollen^^)

http://goo.gl/IO0DC

Falls jemand Lust hat messages zu bauen, nur zu, ich hab am Sonntag Abend grad keine Motivation :P

**Comment by mirc0crim** [comment]
Kann überhaupt jemand eine andere Sprache ausser De und En? Im Gymer wollten sie mir Französisch beibringen...mal schauen was ich noch kann :D
Es wäre noch witzig, wenn man h4x0r als Sprache wählen kann :) das behersche ich auch besser als Fr :P

**Comment by f3lan** [comment]
Hast du in der navi-liste schon einen switcher eingebaut?

**Comment by sbuenzli** [comment]
Minimale Navi-Liste-Erweiterung: https://github.com/sbuenzli/ese2010-team3/commit/928717d816af28ab343a97f6e1afde3870b28711

**Comment by sbuenzli** [comment]
Referenz: http://www.playframework.org/documentation/1.0.3.2/i18n

**Comment by blackyeti-ch** [comment]
http://goo.gl/rKiEn

ich wünsche viel Spass beim lesen... :)

**Comment by f3lan** [comment]
Der Vorschlag: "search question" wird noch nicht übersetzt.

**Comment by mirc0crim** [comment]
so, hat ein paar commits gegeben :D

French: https://github.com/mirco89/ese2010-team3/commit/1ecd44e927f9b2ead94a32e2fc63774ec4aa1641

h4x0r: https://github.com/mirco89/ese2010-team3/commit/2f13f6f01d98e6678758ac9ea752f90aa0ed5f6a

Bug Fix zum ersten: https://github.com/mirco89/ese2010-team3/commit/b496360deb9f8e824ba9775a26628e14e37f1a7b

und zum zweiten: https://github.com/mirco89/ese2010-team3/commit/b1d264e596880236e83f56a9c2570d514b3e5882

viel Spass :D

**Comment by mirc0crim** [comment]
5 minutes ago wird auch noch nicht übersetzt, sehe aber noch nicht wo es das anzupassen gibt

**Comment by sbuenzli** [comment]
Eventuell reicht es, die Message since.seconds, since.minutes, etc. hinzuzufügen, die laut dem Quellcode verwendet werden: https://github.com/playframework/play/blob/master/framework/src/play/templates/JavaExtensions.java#L178

**Comment by mirc0crim** [comment]
Fast! d.h. es wird zwar übersetzt, aber die Zahl wird nichtmehr angezeigt.

**Comment by sbuenzli** [comment]
Dann fehlt in der Übersetzung noch ein %d an der richtigen Stelle: "%d Minuten" (oder so)?

**Comment by mirc0crim** [comment]
yay, danke

**Comment by mirc0crim** [comment]
jetzt sollte alles übersetzt sein.
