### ISSUE TITLE
Fix review comments (by Team 2)

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#66]
Setzt alle Punkte um, die sowohl vom Code review von Team 2 als auch bei den usability Tests der Lektion zum vorschein getreten sind. Schaut dabei auch, dass eure Seite stabil läuft, keine Bugs mehr auftreten, damit wir später an der Performance sauber arbeiten können.

**Comment by mirc0crim** [comment]
Alle Punkte von Code Review von Team 2 könnt ihr auf unserer Wiki Seite durchstreichen:
http://ese.unibe.ch/teams/team3/CodeReviewFromTeam2
Schreibt dazu jeweils einen kurzen Kommentar ob ihrs gefixt habt oder ob der Punkt gar keinen Sinn macht (wie die ersten beiden) ^^

**Comment by tbrog** [comment]
Versuche einfach das zu machen, was ich kann.

**Comment by sbuenzli** [comment]
Die Liste mit den Usability-Issues habe ich in Issue 63 zusammengestellt. Dann bleiben hier bloss die Review-Kommentare von Team 2.

**Comment by f3lan** [comment]
Habe einige Dinge aus dem Issue 63 in Issue 67 schon erledigt.

**Comment by sbuenzli** [comment]
Dieser Issue handelt nicht von den Usability-Tests sondern den Review-Kommentaren von Team 2. Hier fehlt v.a. noch folgendes:
- mayLoggedInUserEditProfileOf umbenamsen
- Controller mit JavaDoc versehen (vorerst mal minimal)
- sicherstellen, dass Session.get().currentUser() etc. höchstens einmal pro Controller-Methode aufgerufen werden
- Secured.java aufteilen auf User.java (für alle mit user, notification und register beginnenden Routes), Question.java (für alle mit question beginnenden Routes) und Answer.java
- editProfile gehört dann nach User.java
- SearchEngine.java mit JavaDoc versehen
- git mv Filter.java IFilter.java (und dann alle Fehler in Eclipse flicken)
- Password in editProfile ändern lassen

**Comment by tbrog** [comment]
https://github.com/tbrog/ese2010-team3/commit/0864892c0f460a6ca29724e8866622f7e33fc714#diff-14

Die SearchEngine wollte ich lieber nicht einfach so mit Javadoc versehen. Der Inhalt der Passwortfelder ist noch sichtbar. 
Der Rest des Javadocs für den Controller kommt noch.

**Comment by tbrog** [comment]
https://github.com/tbrog/ese2010-team3/commit/8981fe75e26fe4a6f775af81b0aca8da91b16dea

Mehr Javadoc. Stellenweise sehr minimal.

**Comment by sbuenzli** [comment]
Wir behalten editProfile vorderhand im Application-Controller, da dieser bisher als einziger Views rendert. Sollten wir diesen je aufbrechen, müssen die einzelnen Views in andere Verzeichnisse verschoben werden und @Before setConnectedUser in die anderen Controller kopiert (bzw. in einen Setup-Controller, von welchem alle anderen erben).

Ansonsten sollten wir hier fertig sein.
