### ISSUE TITLE
include usernames in a search

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#68]
Nach issue: https://github.com/ese-unibe-ch/ese2010-team3/issues#issue/63

include usernames in a search (and maybe also comments so that all primary entities can be searched one way or the other)

**Comment by zombiecalypse** [comment]
- zombiecalypse/ese2010-team3@7e80c1bd3f825741a9dad0c7970f3e239404c452
- zombiecalypse/ese2010-team3@c0116e504fc1de74061d69b251baedb363bda63a
- zombiecalypse/ese2010-team3@e87e67b4a4cc35f29668100d071f120e3dbc7773
  
  ## Search Overview

You get a overview first:
- 3 best questions
- 3 best answers
- 3 best users

Then, if the user's not happy, they can see MOAR.

**Comment by sbuenzli** [comment]
Wenn Du gerade in dem Code bist: das Review von Team 2 fragt nach JavaDoc in SearchEngine bzw. dessen Nachfolger. Du kennst den Code am besten und wärst damit der ideale Kommentator...

**Comment by sbuenzli** [comment]
Die günstige Lösung von Aldi: https://github.com/ese-unibe-ch/ese2010-team3/commit/096b7412a8d5f65652d96a740a5f3300ef6b9319
