### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#7]
Behebung des Bugs, welches durch Merge-Conflict aufgetreten  ist.

**Comment by sbuenzli** [comment]
Zum Reviewen: http://github.com/sbuenzli/ese2010-team3/commit/84f0b9a7c08dcc94f0e8f5f3e96827387991dfae

**Comment by zombiecalypse** [comment]
Sieht gut aus und funktioniert. Hoffen wir, dass das mal der merge glücklicher funktioniert

**Comment by sbuenzli** [comment]
Scheint noch immer zu funktionieren... ;-)
