### ISSUE TITLE
Cron-jobs

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#76]
Ist es eigentlich möglich so etwas wie Cronjobs in play zu implementieren? Ich frage darum, weil bei der Registrierung eines neuen Users eine Zeitlimite fürs bestätigen eingeführt werden sollte... Nur so aus Interesse...

**Comment by sbuenzli** [comment]
Wir könnten die Zeitlimite auch dann testen, wenn der Benutzer den Aktivierungs-Link verwendet (bzw. wenn ein Admin sich die nicht registrierten Benutzer auflistet oder wenn sich ein neuer Benutzer registrieren möchte, etc.)?

Andererseits: http://www.playframework.org/documentation/1.1/jobs#scheduling

**Comment by f3lan** [comment]
So hab mal was gemacht. Bin aber nicht sicher, ob dies so funktioniert.
https://github.com/flangenegger/ese2010-team3/commit/5689daf5c9d21e38521987efbe41547bc6967998
