### ISSUE TITLE
Mail Usability

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#79]
Wie kann man abfragen, ob eine Ex. geworfen wurde, wenn diese schon gecatch wurde?:

https://github.com/flangenegger/ese2010-team3/commit/5473d7a31bd58375ae73b8a4af91bb0dfa9b27df

**Comment by f3lan** [comment]
Konnte es nicht lösen mit isDone(). @sbuenzli: Wie war noch deine andere Lösung genau?
@all: Wenn jemand sonst noch eine Lösung sieht, bitte melden.

Aktueller Stand: http://goo.gl/ZQKdz

**Comment by sbuenzli** [comment]
Meine Lösung: https://github.com/sbuenzli/ese2010-team3/commit/6e64872bad167d5764ca309c2075c04f21ffbedd

**Comment by sbuenzli** [comment]
Bzw.: https://github.com/sbuenzli/ese2010-team3/commit/004fb5a6c509f9c770d30b938f640bc32dbc3726

Hab allerdings nur den Fehler-Fall getestet - keine Ahnung, ob die Lösungen auch im Erfolgs-Fall wie erwartet funktionieren.

**Comment by f3lan** [comment]
it works!

**Comment by f3lan** [comment]
please translate: http://goo.gl/VSxkA

**Comment by mirc0crim** [comment]
Push es auf den Master, dann kann ich es auch übersetzen. Reviewed wurde es ja schon.

**Comment by f3lan** [comment]
Ist auf dem Master....
