### ISSUE TITLE
Register User

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#8]
Behebung des Bugs, welches durch Merge-Conflict aufgetreten ist.

**Comment by sbuenzli** [comment]
http://github.com/ese-unibe-ch/ese2010-team3/commit/e4d0e32f7588ea646f620ce6abbe872a4f6df2d4

**Comment by sbuenzli** [comment]
Da sind meines Erachtens einige Dateien vergessen gegangen, die ich notdürftig mit http://github.com/ese-unibe-ch/ese2010-team3/commit/0d8fe044f55ab8c088e0b0e9c4a5eaa3fbda4eaf nachgeliefert habe.

Mirco: Könntest Du noch einmal kurz überprüfen, ob nun upstream alles korrekt ist?

**Comment by mirc0crim** [comment]
Danke, upstream ist alles korrekt und funktioniert. Ich habe deinen regulären Ausdruck noch erweitert. Hab einen neuen Issue eröffnet, damit du ihn dort reviewen kannst.
