### ISSUE TITLE
SAD

### ISSUE THREAD

**Issue by tbrog** [ese-unibe-ch/ese2010-team3#80]
For the architecture one-pager, you are requested to write a short Software Architecture Document (SAD) according to the 4+1 view model.

**Comment by tbrog** [comment]
Hier das Use Case Diagram
https://github.com/tbrog/ese2010-team3/blob/SAD/Use%20Case.jpg

bitte kritisieren :) die Deployment View kommt noch.

**Comment by tbrog** [comment]
Deployment View:
https://github.com/tbrog/ese2010-team3/blob/SAD/Deployment%20Diagram.jpg

aus den "Umgebungsvariablen" wurde ich nicht ganz schlau.

**Comment by f3lan** [comment]
Der anonyme user kann noch den Account confimen...

**Comment by zombiecalypse** [comment]
sorry, habs nicht früher gesehen, dass wir das im Issue Tracker machen:
https://github.com/zombiecalypse/ese2010-team3/commit/6b6dacb87fe9dc6822743c21327bf4091fd897fd

@felix: stimmt, aber wir machen nur die top10 Usecases und das confirmen ist nicht so essentiell für die Interaktion wie zb das Registrieren

**Comment by f3lan** [comment]
No problem. Da ich das neu eingefügt hatte wollte ich es nur noch erwähnen.
