### ISSUE TITLE
jmeter - Performance Test

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#81]
- http://ese.unibe.ch/exercises/performanceTesting
- http://jakarta.apache.org/jmeter/usermanual/index.html

**Comment by f3lan** [comment]
So scriptchen wurde erstellt und ist auf dem upstream... viel spass!

**Comment by f3lan** [comment]
Mir ist nicht mehr ganz klar, wer die die Schlüsse aus den Tests zieht. Also wer ist zuständig für:
- Results
- Wiki

Ich möchte nicht, dass diese Punkte in Vergessenheit geraten.

**Comment by sbuenzli** [comment]
Einige bescheidene Verbesserungen: https://github.com/sbuenzli/ese2010-team3/commit/d62fd928cf1d34548c1883860e6a7655fec5d413

Den bei weiten wesentlichsten Unterschied zur Performance macht selbstverständlich der Wechsel in den Produktiv-Modus, der bei mir sämtliche Werte fünftelt.

Da die Tests bei derselben Frage immer mehr Antworten hinzufügen, müsste Play! eigentlich nach jedem Durchgang neu gestartet werden, um vergleichbare Werte zu erhalten. Da ich bisher noch keinen vernünftigen Profiler für Play! gefunden haben, sehe ich kaum, wie wir hier sinnvoll zu Performance-Verbesserungen kommen könnten.

**Comment by tbrog** [comment]
http://ese.unibe.ch/teams/team3/PerformanceTesting

**Comment by sbuenzli** [comment]
Danke, Tobias.
