### ISSUE TITLE
improve search/post delay UX

### ISSUE THREAD

**Issue by sbuenzli** [ese-unibe-ch/ese2010-team3#82]
For review:
- https://github.com/sbuenzli/ese2010-team3/commit/663a2541b98d7644cad5b9a7cd1ef5cbba55487c
- https://github.com/sbuenzli/ese2010-team3/commit/7ac606c59875980b711b4b385058c3ae0b512d05
- https://github.com/sbuenzli/ese2010-team3/commit/553f59d368ab82c5bb5e554a21d0e34020ef7fbe
- https://github.com/sbuenzli/ese2010-team3/commit/b7a748d2ca2d21f13282c1b3f050d4e08e361120

**Comment by mirc0crim** [comment]
gut, die paar backslashes escapen und ab auf den master damit :)

**Comment by sbuenzli** [comment]
Backslashes: https://github.com/ese-unibe-ch/ese2010-team3/commit/f15fe836e5dd2d6cd293240065d00fa504576570
