### ISSUE TITLE
Mark "Spam"

### ISSUE THREAD

**Issue by zombiecalypse** [ese-unibe-ch/ese2010-team3#83]
Users should be able to mark entries as spam, which then gives the moderators a notification. A mod can then decide, that a certain user is a spammer and the entry should be removed (at least from the view of the users).

When a user is marked as spammer, all users can mark his posts as spam without further checks needed by the mods, so that the posts are removed.

As Moderators might become quite stressed out, if they get notifications for every spam-marking even if it is already acted upon, all mods should have the same point of access to this special notifications, so that the "read" flag propagates through all notification boxes of the moderators.

**Comment by zombiecalypse** [comment]
First step: creating Mailboxes that can be shared among users:
zombiecalypse/ese2010-team3@e84fff6f8d995d13b766

**Comment by zombiecalypse** [comment]
Other Steps: 
- zombiecalypse/ese2010-team3@7496cc885cb5070dd243
- zombiecalypse/ese2010-team3@98cf0ddac34b59550e1b
- zombiecalypse/ese2010-team3@d7dad0e2f200e2fdbaa3
- zombiecalypse/ese2010-team3@2afc9d8ebc8a9afff5cc
- zombiecalypse/ese2010-team3@f76705cadd43c5ccf21e

Sorry for the commit-spam, but there always seemed to be some thing I missed the first time.

**Comment by sbuenzli** [comment]
Hier fehlen noch Übersetzungen, damit wir unseren Kunden nicht zwingen müssen, das neue Feature auf Englisch zu testen.
