### ISSUE TITLE
Strange Bug

### ISSUE THREAD

**Issue by f3lan** [ese-unibe-ch/ese2010-team3#85]
1. Login as John
2. Click on 4 question
3. Error:
   
      Cache error
      Cannot cache a non-serializable value of type java.util.ArrayList$SubList
      In /app/controllers/Application.java (around line 80)

**Comment by mirc0crim** [comment]
Der User ist egal. Jack bekommt die selbe Fehlermeldung.
Es liegt an der 4. Frage von "sdaau" welche irgendwie nicht gecached werden kann.

**Comment by f3lan** [comment]
Ach so... es sind wohl zuviele.

**Comment by f3lan** [comment]
Bugfix: (caution: ugly!)

http://goo.gl/aezhC

**Comment by sbuenzli** [comment]
Ja, keine Sublists für den Cache...
