### ISSUE TITLE
Bootstrap Weirdness

### ISSUE THREAD

**Issue by zombiecalypse** [ese-unibe-ch/ese2010-team3#87]
In the bootstrap when the initial questions and answers are loaded, "Recent <Item>" are not adequately updated. It is to be assumed, that there are other problems as well.

Items in the bootstrap should be treated in the exact same way as posted questions.

**Comment by sbuenzli** [comment]
For review: https://github.com/sbuenzli/ese2010-team3/commit/30b2bbde058dfc466d5e4b4c2602735bc9286f5b

**Comment by sbuenzli** [comment]
Und wenn ich mir schon mal die Controller vorgenommen habe:
- https://github.com/sbuenzli/ese2010-team3/commit/19bd0c3b7f9e88de35e94fec83a50f933416317a
- https://github.com/sbuenzli/ese2010-team3/commit/1a99ecdc667583e0e474c683666a1bf38fb1c830
