### ISSUE TITLE
Notification Bar

### ISSUE THREAD

**Issue by zombiecalypse** [ese-unibe-ch/ese2010-team3#88]
The customer would would like to have a one click access point for (all) new notifications. 

A sidebar (right), should show all new notifications.

**Comment by f3lan** [comment]
OK habe mal die sidebar erstellt:

http://goo.gl/Z2Per

@tbrog: Nun müssen noch die Notifications folgen

**Comment by f3lan** [comment]
corrections:

http://goo.gl/PJKdy

Habe noch ein Problem mit dem javascript

**Comment by f3lan** [comment]
Blicke mit dem javascript nicht mehr durch!

http://goo.gl/MtcE8

**Comment by f3lan** [comment]
So jetzt ist es von mir aus ok.

http://goo.gl/uMISW

**Comment by f3lan** [comment]
now ready für tbrog! :)

**Comment by tbrog** [comment]
https://github.com/tbrog/ese2010-team3/commit/c1a9fd962a1b6cfe7d488cefce68d88f7a7c2876

Das unterscheidet einfach nicht zwischen den Notifications und würde auch beliebig viele neue Notifications anzeigen.

**Comment by tbrog** [comment]
https://github.com/tbrog/ese2010-team3/commit/f446ba356325f99932a74cef630233d01ae050b4#commitcomment-223292

Der Kunde wollte ja "alle" notifications, deshalb habe ich noch so belassen, allerdings wäre es nicht schön, wenn die Sidebar dann unten hinausragen würde...

**Comment by sbuenzli** [comment]
Nach unten haben wir eigentlich Platz. Weitere Kundenwünsche können wir dann nächstes Jahr erfüllen. ;-)

**Comment by tbrog** [comment]
Hier: https://github.com/tbrog/ese2010-team3/commit/62befc6c0f2381018e01ba68fe0732afb9c8f166

Vielleicht wäre ein Hover-Effekt noch ganz schön, aber ich habe das nicht zustande gebracht.

**Comment by tbrog** [comment]
Hier die Änderungen. Mit Hover hats komisch ausgesehen: https://github.com/tbrog/ese2010-team3/commit/62b1880481bd0b9344dc586b772065029a89f7a0

**Comment by sbuenzli** [comment]
Damit ist ajopi _feature complete_!
