### ISSUE TITLE
Update the Wikipage

### ISSUE THREAD

**Issue by zombiecalypse** [ese-unibe-ch/ese2010-team3#90]
The wiki should be up to date about the current state of the project. 
- Weekly reports
- Release note
- Whitepaper

**Comment by blackyeti-ch** [comment]
Started with the specifications for the release notes according to our issues on github.
http://goo.gl/mV06k

If you see something completely missing, feel free to write it down.

btw, if you want avatar pictures in the whitepaper you can insert them here: http://goo.gl/NDDhS (Section "The Team")
They're recommended for the basic structure - http://goo.gl/pS1zc (see "The Team")

**Comment by blackyeti-ch** [comment]
The whitepaper is now mostly done, if you come up with some catchy sentences or corrections feel free to edit :)
We also should have 2 more highlights (we should have 10) on the list and some sentences about us.
http://goo.gl/vcYOd

/edit: i guess someone just edited something since I got a merge fail, please check your changes^^

**Comment by sbuenzli** [comment]
Thanks for the whitepaper and sorry about that merge fail!

**Comment by sbuenzli** [comment]
Please check and/or rewrite your mini-biographies in the whitepaper (1-3 catchy sentences about your involvement in the team).

**Comment by sbuenzli** [comment]
BTW: The Release Notes are still missing instructions for how to configure a mail server and for how to create new users and administrators.

**Comment by sbuenzli** [comment]
Now, all that's left is tagging v2.0 so that the download link in the whitepaper actually works. I'd however recommend you to go through all the features (and maybe also my last few pushes) one more time before actually doing that...
