### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by zombiecalypse** [ese-unibe-ch/ese2010-team3#91]
We need a 5min presentation. Free choice of medium.

**Comment by mirc0crim** [comment]
Was haben wir für features die die anderen Teams nicht haben?
Wir präsentieren ja wohl nicht die standart Sachen?!
Dass man sich als Jack oder JaCk einloggen kann...das ist wohl ein paar Worte wert.
Was noch??

**Comment by zombiecalypse** [comment]
Email Aktivierung, auch wenn das dem User nicht viel bringt. Unsere Anti-Spam-mechanismen sind glaubs auch gut und das Design. Aber eigentlich gibt es keine Features, die wirklich für den User aussergewöhnlich sind. Tags helfen, sind aber nicht aussergewöhnlich, Suche nach ähnlichen Fragen ist wohl noch erwähnenswert und unser Expertise-System. Aber ich weiss nicht, was unsere "Konkurenz" alles hat...

**Comment by sbuenzli** [comment]
Wir sollten in jedem Fall versuchen, mit Chrome zu präsentieren, damit auch unsere HTML5-Verbesserungen zur Geltung kommen.

Und was auch immer wir präsentieren, prüft doch bitte zuerst, ob das Feature tatsächlich (immer noch) funktioniert. U.a. die E-Mail-Registrierung war heute morgen defekt...

**Comment by f3lan** [comment]
Was war genau defekt bei der E-mail-Registrierung?

**Comment by sbuenzli** [comment]
Ein Tipp-Fehler und ein Merge-Fehler im Zusammenhang mit den CAPTCHAs: https://github.com/ese-unibe-ch/ese2010-team3/commit/10d6f859ce576f63b2ca2f683270fa2f479dc9d7#diff-0
